sudo: false
language: python
python:
  - "2.7"
branches:
  only:
    - staging
    - master

install:
  # for fontmake
  - git clone https://github.com/googlei18n/fontmake.git
  - cd fontmake
  - pip install -r requirements.txt
  - python setup.py install
  - cd ..
  # for notodiff
  - wget https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-1.3.2.tar.bz2
  - tar xjf harfbuzz-1.3.2.tar.bz2
  - cd harfbuzz-1.3.2
  - ./configure
  - make
  - PATH="${PATH}:$(pwd)/util"
  - cd ..
  - git clone https://github.com/googlei18n/nototools.git
  - cd nototools
  - python setup.py install
  - cd ..
  # for fontdiff
  - wget https://github.com/googlei18n/fontdiff/releases/download/v0.1.1/fontdiff-linux.zip
  - unzip fontdiff-linux.zip
  - mv fontdiff-linux/fontdiff .

script:
  - bash ./build_travis.sh
